version: "3.9"

services:
  ganache:
    image: trufflesuite/ganache:7.9.2 
    container_name: ganache
    ports:
      - "8545:8545"
    command:
      - --host=0.0.0.0
      - --port=8545
      - --mnemonic="test test test test test test test test test test test junk"
      - --db=/data
    volumes:
      - ganache_data:/data

volumes:
  ganache_data: